### ISSUE TITLE
1.17.1 crashes in Message Requests

### ISSUE THREAD

**Issue by 2011** [oxen-io/session-android#1317]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Session crashes 100 percent of the time when I attempt to select a message request.

**To reproduce**

Start the app.
Tap on Message Requests.
Long tap on a message request

**Screenshots or logs**

```
[09-05 04:45:33.646 19599:20623 I/ActivityManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=network.loki.messenger/org.thoughtcrime.securesms.home.HomeActivity} from uid 10011 on display 0

[09-05 04:45:33.646 19599:20623 W/ActivityManager]
Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=network.loki.messenger/org.thoughtcrime.securesms.home.HomeActivity } from null (pid=-1, uid=10011) not exported from uid 10022

[09-05 04:45:33.648 20286:20286 E/SystemServicesProxy]
Could not start Session.
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=network.loki.messenger/org.thoughtcrime.securesms.home.HomeActivity } from null (pid=-1, uid=10011) not exported from uid 10022
        at android.os.Parcel.readException(Parcel.java:1683)
        at android.os.Parcel.readException(Parcel.java:1636)
        at android.app.ActivityManagerProxy.startActivityFromRecents(ActivityManagerNative.java:3353)
        at com.android.systemui.recents.misc.SystemServicesProxy.startActivityFromRecents(SystemServicesProxy.java:985)
        at com.android.systemui.recents.views.RecentsTransitionHelper.startTaskActivity(RecentsTransitionHelper.java:202)
        at com.android.systemui.recents.views.RecentsTransitionHelper.launchTaskFromRecents(RecentsTransitionHelper.java:167)
        at com.android.systemui.recents.views.RecentsView.onBusEvent(RecentsView.java:449)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.systemui.recents.events.EventHandlerMethod.invoke(EventBus.java:104)
        at com.android.systemui.recents.events.EventBus.processEvent(EventBus.java:877)
        at com.android.systemui.recents.events.EventBus.queueEvent(EventBus.java:836)
        at com.android.systemui.recents.events.EventBus.send(EventBus.java:571)
        at com.android.systemui.recents.views.TaskView.onClick(TaskView.java:657)
        at android.view.View.performClick(View.java:5609)
        at android.view.View$PerformClick.run(View.java:22262)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

[09-05 04:45:36.986 19599:20116 I/ActivityManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=network.loki.messenger/.RoutingActivity bnds=[2,1812][268,2223]} from uid 10011 on display 0

[09-05 04:45:37.031 19599:19614 I/ActivityManager]
Start proc 30127:network.loki.messenger/u0a22 for activity network.loki.messenger/.RoutingActivity

[09-05 04:45:37.462 30127:30156 D/Loki-Avatar]
Uploading Avatar Started

[09-05 04:45:37.476 30127:30156 E/Loki-Avatar]
Uploading avatar failed
java.io.FileNotFoundException: /data/user/0/network.loki.messenger/files/avatars/[Session ID redacted] (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at org.session.libsession.avatars.AvatarHelper.getInputStreamFor(AvatarHelper.java:27)
        at org.thoughtcrime.securesms.ApplicationContext.lambda$resubmitProfilePictureIfNeeded$4$org-thoughtcrime-securesms-ApplicationContext(ApplicationContext.java:465)
        at org.thoughtcrime.securesms.ApplicationContext$$ExternalSyntheticLambda6.run(D8$$SyntheticClass)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

[09-05 04:45:39.591 30127:30161 D/Loki]
Started polling.

[09-05 04:45:39.617 30127:30168 D/Loki]
Polling https://167.86.73.98:22021.

[09-05 04:45:40.100 19599:19643 I/ActivityManager]
Displayed network.loki.messenger/.RoutingActivity: +3s87ms

[09-05 04:45:40.143 19599:19643 I/WindowManager]
Destroying surface Surface(name=Starting network.loki.messenger) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.AppWindowToken.destroySurfaces:363 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:491 com.android.server.wm.WindowAnimator.updateWindowsLocked:303 com.android.server.wm.WindowAnimator.animateLocked:704 

[09-05 04:45:41.488 19599:19613 I/ActivityManager]
START u0 {cmp=network.loki.messenger/org.thoughtcrime.securesms.messagerequests.MessageRequestsActivity} from uid 10022 on display 0

[09-05 04:45:41.794 19599:19643 I/ActivityManager]
Displayed network.loki.messenger/org.thoughtcrime.securesms.messagerequests.MessageRequestsActivity: +281ms

[09-05 04:45:41.876 19599:21154 I/WindowManager]
Destroying surface Surface(name=network.loki.messenger/network.loki.messenger.RoutingActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.WindowManagerService.tryStartExitingAnimation:3021 com.android.server.wm.WindowManagerService.relayoutWindow:2901 com.android.server.wm.Session.relayout:215 android.view.IWindowSession$Stub.onTransact:286 com.android.server.wm.Session.onTransact:136 

[09-05 04:45:43.257 30127:30127 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: network.loki.messenger, PID: 30127
java.lang.NoSuchMethodError: No interface method setIconTintList(Landroid/content/res/ColorStateList;)Landroid/view/MenuItem; in class Landroid/view/MenuItem; or its super classes (declaration of 'android.view.MenuItem' appears in /system/framework/framework.jar:classes2.dex)
        at org.thoughtcrime.securesms.messagerequests.MessageRequestsAdapter.showPopupMenu(MessageRequestsAdapter.kt:64)
        at org.thoughtcrime.securesms.messagerequests.MessageRequestsAdapter.onCreateItemViewHolder$lambda$3(MessageRequestsAdapter.kt:32)
        at org.thoughtcrime.securesms.messagerequests.MessageRequestsAdapter.$r8$lambda$g0hyaEezphOjgNVwFgYiqcqnD5c(MessageRequestsAdapter.kt)
        at org.thoughtcrime.securesms.messagerequests.MessageRequestsAdapter$$ExternalSyntheticLambda1.onLongClick(D8$$SyntheticClass)
        at android.view.View.performLongClickInternal(View.java:5686)
        at android.view.View.performLongClick(View.java:5644)
        at android.view.View.performLongClick(View.java:5662)
        at android.view.View$CheckForLongPress.run(View.java:22231)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

[09-05 04:45:43.259 19599:26275 W/ActivityManager]
  Force finishing activity network.loki.messenger/org.thoughtcrime.securesms.messagerequests.MessageRequestsActivity

[09-05 04:45:43.772 19599:19626 W/ActivityManager]
Activity pause timeout for ActivityRecord{ab61bfc u0 network.loki.messenger/org.thoughtcrime.securesms.messagerequests.MessageRequestsActivity t4102 f}

[09-05 04:45:45.319 19599:26275 W/ActivityManager]
  Force finishing activity network.loki.messenger/org.thoughtcrime.securesms.messagerequests.MessageRequestsActivity

[09-05 04:45:45.324 19599:26275 W/ActivityManager]
  Force finishing activity network.loki.messenger/.RoutingActivity

[09-05 04:45:45.367 19599:26275 E/ActivityManager]
Found activity ActivityRecord{2ba9f9c u0 network.loki.messenger/.RoutingActivity t4102 f} in proc activity list using null instead of expected ProcessRecord{7e0212a 30127:network.loki.messenger/u0a22}

[09-05 04:45:45.370 19599:26275 I/ActivityManager]
Killing 30127:network.loki.messenger/u0a22 (adj 199): crash

[09-05 04:45:45.376 19599:19643 I/WindowManager]
Destroying surface Surface(name=Application Error: network.loki.messenger) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner:429 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:232 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:180 com.android.server.wm.WindowManagerService$H.handleMessage:8115 android.os.Handler.dispatchMessage:102 

[09-05 04:45:45.382 19599:19643 I/WindowManager]
Destroying surface Surface(name=network.loki.messenger/org.thoughtcrime.securesms.messagerequests.MessageRequestsActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2482 com.android.server.wm.WindowManagerService.removeWindowLocked:2440 com.android.server.wm.WindowManagerService.removeWindowLocked:2309 com.android.server.wm.AppWindowToken.removeAllWindows:530 com.android.server.wm.AppWindowToken.removeAppFromTaskLocked:326
```

**Smartphone (please complete the following information):**

 - Device: Teclast T10
 - OS: Android 7.0
 - Version of Session: 1.17.1

**Comment by hjubb** [comment]
This might be an OS specific issue we can work around, will look more into it

**Comment by KeeJef** [comment]
Unable to reproduce on my side

**Comment by KeeJef** [comment]
Is this still occurring on latest Android version 1.19.2?

**Comment by 2011** [comment]
> Is this still occurring on latest Android version 1.19.2?

Sorry for the delay in replying. No, the problem no longer occurs on Android version 1.19.1 (and it appears that I will remain on semi-permanently on 1.19.1, as subsequent versions require a minimum of Android 8).
