### ISSUE TITLE
Fast Mode for Huawei devices not working

### ISSUE THREAD

**Issue by m1chj** [oxen-io/session-android#1320]
**Code of conduct**

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Push notifications for Huawei utilizing their servers don't work with Fast Mode. New messages show once the app is in the foreground but even then there's no notification popups, just chats numbers showing there's some unread messages

**To reproduce**

1. Own (any?) modern and google-free Huawei phone
2. Download Session from AppGallery or github - version dedicated for Huaweis
3. Set notifications to Fast Mode, it's default anyway
4. Fail to receive push notifications whenever you receive a message

**Logs**

https://drive.filen.io/d/cc7b2417-d70a-4062-9dbf-c37282d75fb6#WjCMymth8WGCUrmulK1BQ8RRPyrcfBnK

**Smartphone:**

 - Device: Huawei P40 series but it likely doesn't matter as it's the same thing on another goolag-free Huawei
 - OS: EMUI 12 based on android 10
 - Version 1.17.1 (3555)

**Additional context**

It was working just fine for a day or two after release iirc

**Comment by m1chj** [comment]
Logs for convenience:

2023-09-09 22:47:20.625 GMT+02:00 E ThemeUtil: Couldn't find a color attribute with id: 2130968844
2023-09-09 22:47:20.636 GMT+02:00 V BackgroundPollWorker: Scheduling periodic work.
2023-09-09 22:47:20.752 GMT+02:00 I PassphraseRequiredActionBarActivity: onCreate(null)
2023-09-09 22:47:20.753 GMT+02:00 I PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
2023-09-09 22:47:20.778 GMT+02:00 I PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
2023-09-09 22:47:22.266 GMT+02:00 I ApplicationContext: App is now visible.
2023-09-09 22:47:22.269 GMT+02:00 D Loki: Started polling.
2023-09-09 22:47:22.272 GMT+02:00 D org.thoughtcrime.securesms.notifications.PushRegistry: refresh() called with: force = false
2023-09-09 22:47:22.284 GMT+02:00 D Loki: Polling https://5.161.76.6:22021.
2023-09-09 22:47:22.385 GMT+02:00 D tx: processJob: ConfigurationSyncJob (id: 16942924422960)
2023-09-09 22:47:22.581 GMT+02:00 V BackgroundPollWorker: Skipping initial run.
2023-09-09 22:47:22.618 GMT+02:00 V BackgroundPollWorker: Performing background poll for DMS, CLOSED_GROUPS, OPEN_GROUPS.
2023-09-09 22:47:22.751 GMT+02:00 D org.thoughtcrime.securesms.notifications.PushRegistry: refresh() called
2023-09-09 22:47:22.806 GMT+02:00 D org.thoughtcrime.securesms.notifications.PushRegistry: register() called
2023-09-09 22:47:22.826 GMT+02:00 D org.session.libsession.messaging.sending_receiving.notifications.PushRegistryV1: register() called
2023-09-09 22:47:22.826 GMT+02:00 D org.session.libsession.messaging.sending_receiving.notifications.PushRegistryV1: doRegister() called
2023-09-09 22:47:25.402 GMT+02:00 D Loki: Finished preloading onion request path countries.
2023-09-09 22:47:26.118 GMT+02:00 D org.session.libsession.messaging.sending_receiving.notifications.PushRegistryV1: registerV1 success
2023-09-09 22:47:26.540 GMT+02:00 I BatchMessageReceiveJob: Completed processing of 1 messages (id: null)
2023-09-09 22:47:28.295 GMT+02:00 D tx: processJob: ConfigurationSyncJob (id: 16942924482910)
2023-09-09 22:47:30.047 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
2023-09-09 22:47:30.076 GMT+02:00 I PassphraseRequiredActionBarActivity: onCreate(null)
2023-09-09 22:47:30.102 GMT+02:00 I PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
2023-09-09 22:47:30.102 GMT+02:00 I PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
2023-09-09 22:47:30.708 GMT+02:00 D tx: processJob: MessageSendJob (id: 16942924506970)
2023-09-09 22:47:31.593 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
2023-09-09 22:47:31.999 GMT+02:00 I PassphraseRequiredActionBarActivity: onDestroy()
2023-09-09 22:47:32.855 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
2023-09-09 22:47:32.878 GMT+02:00 I PassphraseRequiredActionBarActivity: onCreate(null)
2023-09-09 22:47:32.879 GMT+02:00 I PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
2023-09-09 22:47:32.882 GMT+02:00 I PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
2023-09-09 22:47:32.936 GMT+02:00 D tx: processJob: ConfigurationSyncJob (id: 16942924512920)
2023-09-09 22:47:33.132 GMT+02:00 D ConfigSyncJob: Including delete request for current hashes
2023-09-09 22:47:33.751 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
2023-09-09 22:47:34.164 GMT+02:00 I PassphraseRequiredActionBarActivity: onDestroy()
2023-09-09 22:47:35.600 GMT+02:00 D ConfigSyncJob: Hash KDVx returned from store request for new config
2023-09-09 22:47:35.616 GMT+02:00 D ConfigSyncJob: Successfully removed the deleted hashes from ConversationVolatileConfig
2023-09-09 22:47:35.632 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: register v2 failed
2023-09-09 22:47:35.632 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: java.lang.Exception: error: huawei notification service not currently available.
2023-09-09 22:47:35.632 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at org.thoughtcrime.securesms.notifications.PushRegistryV2$register$$inlined$retryResponseBody$1$1.invoke(PushRegistryV2.kt:113)
2023-09-09 22:47:35.632 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at org.thoughtcrime.securesms.notifications.PushRegistryV2$register$$inlined$retryResponseBody$1$1.invoke(PushRegistryV2.kt:110)
2023-09-09 22:47:35.632 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at nl.komponents.kovenant.ThenPromise$schedule$wrapper$1.invoke(promises-jvm.kt:98)
2023-09-09 22:47:35.632 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at nl.komponents.kovenant.ThenPromise$schedule$wrapper$1.invoke(promises-jvm.kt:63)
2023-09-09 22:47:35.632 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at nl.komponents.kovenant.jvm.KovenantJvmApi$sam$Runnable$369ad934.run(Unknown Source:2)
2023-09-09 22:47:35.632 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2023-09-09 22:47:35.632 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2023-09-09 22:47:35.632 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at java.lang.Thread.run(Thread.java:929)
2023-09-09 22:47:35.682 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: register failed
2023-09-09 22:47:35.682 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: java.lang.Exception: error: huawei notification service not currently available.
2023-09-09 22:47:35.682 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at org.thoughtcrime.securesms.notifications.PushRegistryV2$register$$inlined$retryResponseBody$1$1.invoke(PushRegistryV2.kt:113)
2023-09-09 22:47:35.682 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at org.thoughtcrime.securesms.notifications.PushRegistryV2$register$$inlined$retryResponseBody$1$1.invoke(PushRegistryV2.kt:110)
2023-09-09 22:47:35.682 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at nl.komponents.kovenant.ThenPromise$schedule$wrapper$1.invoke(promises-jvm.kt:98)
2023-09-09 22:47:35.682 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at nl.komponents.kovenant.ThenPromise$schedule$wrapper$1.invoke(promises-jvm.kt:63)
2023-09-09 22:47:35.682 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at nl.komponents.kovenant.jvm.KovenantJvmApi$sam$Runnable$369ad934.run(Unknown Source:2)
2023-09-09 22:47:35.682 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2023-09-09 22:47:35.682 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2023-09-09 22:47:35.682 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at java.lang.Thread.run(Thread.java:929)
2023-09-09 22:47:36.429 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
2023-09-09 22:47:36.450 GMT+02:00 I PassphraseRequiredActionBarActivity: onCreate(null)
2023-09-09 22:47:36.450 GMT+02:00 I PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
2023-09-09 22:47:36.462 GMT+02:00 I PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
2023-09-09 22:47:36.755 GMT+02:00 D rx: processJob: BatchMessageReceiveJob (id: 16942924567530)
2023-09-09 22:47:36.808 GMT+02:00 I BatchMessageReceiveJob: Couldn't receive message, failed with error: Message addressed at self. (id: 16942924567530)
2023-09-09 22:47:36.818 GMT+02:00 I BatchMessageReceiveJob: Completed processing of 1 messages (id: 16942924567530)
2023-09-09 22:47:38.253 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
2023-09-09 22:47:38.271 GMT+02:00 I PassphraseRequiredActionBarActivity: onCreate(null)
2023-09-09 22:47:38.281 GMT+02:00 I PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
2023-09-09 22:47:38.282 GMT+02:00 I PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
2023-09-09 22:47:40.254 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
2023-09-09 22:47:42.611 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
2023-09-09 22:47:43.008 GMT+02:00 I PassphraseRequiredActionBarActivity: onDestroy()
2023-09-09 22:47:43.239 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
2023-09-09 22:47:43.294 GMT+02:00 D tx: processJob: ConfigurationSyncJob (id: 16942924632920)
2023-09-09 22:47:43.641 GMT+02:00 I PassphraseRequiredActionBarActivity: onDestroy()
2023-09-09 22:47:44.577 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
2023-09-09 22:47:45.278 GMT+02:00 I ApplicationContext: App is no longer visible.
2023-09-09 22:47:45.279 GMT+02:00 D Loki: Stopped polling.
2023-09-09 22:47:45.310 GMT+02:00 E Loki: Failed to get raw batch response
2023-09-09 22:47:45.310 GMT+02:00 E Loki: org.session.libsession.messaging.sending_receiving.pollers.PromiseCanceledException: Promise canceled.
2023-09-09 22:47:45.310 GMT+02:00 E Loki: 	at org.session.libsession.messaging.sending_receiving.pollers.Poller.poll(Poller.kt:168)
2023-09-09 22:47:45.310 GMT+02:00 E Loki: 	at org.session.libsession.messaging.sending_receiving.pollers.Poller.access$poll(Poller.kt:38)
2023-09-09 22:47:45.310 GMT+02:00 E Loki: 	at org.session.libsession.messaging.sending_receiving.pollers.Poller$poll$1$1$5.invoke(Poller.kt:262)
2023-09-09 22:47:45.310 GMT+02:00 E Loki: 	at org.session.libsession.messaging.sending_receiving.pollers.Poller$poll$1$1$5.invoke(Poller.kt:205)
2023-09-09 22:47:45.310 GMT+02:00 E Loki: 	at nl.komponents.kovenant.functional.KovenantFnMoniadic$bindAsync$1.invoke(moniadic.kt:109)
2023-09-09 22:47:45.310 GMT+02:00 E Loki: 	at nl.komponents.kovenant.functional.KovenantFnMoniadic$bindAsync$1.invoke(Unknown Source:0)
2023-09-09 22:47:45.310 GMT+02:00 E Loki: 	at nl.komponents.kovenant.jvm.KovenantJvmApi$sam$Runnable$369ad934.run(Unknown Source:2)
2023-09-09 22:47:45.310 GMT+02:00 E Loki: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2023-09-09 22:47:45.310 GMT+02:00 E Loki: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2023-09-09 22:47:45.310 GMT+02:00 E Loki: 	at java.lang.Thread.run(Thread.java:929)
2023-09-09 22:48:53.898 GMT+02:00 I ApplicationContext: App is now visible.
2023-09-09 22:48:53.912 GMT+02:00 D Loki: Started polling.
2023-09-09 22:48:53.921 GMT+02:00 D Loki: Polling https://161.97.92.0:22021.
2023-09-09 22:48:54.774 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
2023-09-09 22:48:54.799 GMT+02:00 I PassphraseRequiredActionBarActivity: onCreate(null)
2023-09-09 22:48:54.800 GMT+02:00 I PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
2023-09-09 22:48:54.806 GMT+02:00 I PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
2023-09-09 22:48:55.292 GMT+02:00 D tx: processJob: ConfigurationSyncJob (id: 16942925352910)
2023-09-09 22:48:56.905 GMT+02:00 I EarlyReceiptCache: org.thoughtcrime.securesms.database.EarlyReceiptCache@62393df
2023-09-09 22:48:56.907 GMT+02:00 I EarlyReceiptCache: Checking early receipts (1694292535161): 0
2023-09-09 22:48:56.907 GMT+02:00 I EarlyReceiptCache: org.thoughtcrime.securesms.database.EarlyReceiptCache@1ae182c
2023-09-09 22:48:56.908 GMT+02:00 I EarlyReceiptCache: Checking early receipts (1694292535161): 0
2023-09-09 22:48:56.922 GMT+02:00 D tx: processJob: MessageSendJob (id: 16942925369170)
2023-09-09 22:48:56.925 GMT+02:00 I MessageDatabase: Updating ID: 10 to base type: 22
2023-09-09 22:48:57.621 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
2023-09-09 22:48:57.633 GMT+02:00 I PassphraseRequiredActionBarActivity: onDestroy()
2023-09-09 22:48:57.672 GMT+02:00 I PassphraseRequiredActionBarActivity: onCreate(null)
2023-09-09 22:48:57.673 GMT+02:00 I PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
2023-09-09 22:48:57.683 GMT+02:00 I PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
2023-09-09 22:48:57.719 GMT+02:00 D org.thoughtcrime.securesms.notifications.PushRegistry: refresh() called with: force = false
2023-09-09 22:48:57.719 GMT+02:00 D Loki: resumePendingJobs() should only be called once.
2023-09-09 22:48:57.849 GMT+02:00 D org.thoughtcrime.securesms.notifications.PushRegistry: refresh() called
2023-09-09 22:48:57.885 GMT+02:00 D org.thoughtcrime.securesms.notifications.PushRegistry: register() called
2023-09-09 22:48:57.885 GMT+02:00 D org.session.libsession.messaging.sending_receiving.notifications.PushRegistryV1: register() called
2023-09-09 22:48:57.885 GMT+02:00 D org.session.libsession.messaging.sending_receiving.notifications.PushRegistryV1: doRegister() called
2023-09-09 22:48:58.196 GMT+02:00 I PassphraseRequiredActionBarActivity: onDestroy()
2023-09-09 22:48:59.573 GMT+02:00 I MessageDatabase: Updating ID: 10 to base type: 10485783
2023-09-09 22:48:59.605 GMT+02:00 I MessageDatabase: Updating ID: 10 to base type: 29
2023-09-09 22:48:59.745 GMT+02:00 D tx: processJob: ConfigurationSyncJob (id: 16942925382920)
2023-09-09 22:48:59.806 GMT+02:00 D tx: processJob: NotifyPNServerJob (id: 16942925397280)
2023-09-09 22:49:01.851 GMT+02:00 D org.session.libsession.messaging.sending_receiving.notifications.PushRegistryV1: registerV1 success
2023-09-09 22:49:02.605 GMT+02:00 I MessageDatabase: Updating ID: 10 to base type: 10485783
2023-09-09 22:49:03.646 GMT+02:00 D rx: processJob: BatchMessageReceiveJob (id: 16942925436430)
2023-09-09 22:49:03.724 GMT+02:00 I BatchMessageReceiveJob: Couldn't receive message, failed with error: Duplicate message. (id: 16942925436430)
2023-09-09 22:49:03.741 GMT+02:00 I BatchMessageReceiveJob: Completed processing of 1 messages (id: 16942925436430)
2023-09-09 22:49:07.995 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
2023-09-09 22:49:08.413 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: register v2 failed
2023-09-09 22:49:08.413 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: java.lang.Exception: error: huawei notification service not currently available.
2023-09-09 22:49:08.413 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at org.thoughtcrime.securesms.notifications.PushRegistryV2$register$$inlined$retryResponseBody$1$1.invoke(PushRegistryV2.kt:113)
2023-09-09 22:49:08.413 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at org.thoughtcrime.securesms.notifications.PushRegistryV2$register$$inlined$retryResponseBody$1$1.invoke(PushRegistryV2.kt:110)
2023-09-09 22:49:08.413 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at nl.komponents.kovenant.ThenPromise$schedule$wrapper$1.invoke(promises-jvm.kt:98)
2023-09-09 22:49:08.413 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at nl.komponents.kovenant.ThenPromise$schedule$wrapper$1.invoke(promises-jvm.kt:63)
2023-09-09 22:49:08.413 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at nl.komponents.kovenant.jvm.KovenantJvmApi$sam$Runnable$369ad934.run(Unknown Source:2)
2023-09-09 22:49:08.413 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2023-09-09 22:49:08.413 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2023-09-09 22:49:08.413 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at java.lang.Thread.run(Thread.java:929)
2023-09-09 22:49:08.416 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: register failed
2023-09-09 22:49:08.416 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: java.lang.Exception: error: huawei notification service not currently available.
2023-09-09 22:49:08.416 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at org.thoughtcrime.securesms.notifications.PushRegistryV2$register$$inlined$retryResponseBody$1$1.invoke(PushRegistryV2.kt:113)
2023-09-09 22:49:08.416 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at org.thoughtcrime.securesms.notifications.PushRegistryV2$register$$inlined$retryResponseBody$1$1.invoke(PushRegistryV2.kt:110)
2023-09-09 22:49:08.416 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at nl.komponents.kovenant.ThenPromise$schedule$wrapper$1.invoke(promises-jvm.kt:98)
2023-09-09 22:49:08.416 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at nl.komponents.kovenant.ThenPromise$schedule$wrapper$1.invoke(promises-jvm.kt:63)
2023-09-09 22:49:08.416 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at nl.komponents.kovenant.jvm.KovenantJvmApi$sam$Runnable$369ad934.run(Unknown Source:2)
2023-09-09 22:49:08.416 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2023-09-09 22:49:08.416 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2023-09-09 22:49:08.416 GMT+02:00 E org.thoughtcrime.securesms.notifications.PushRegistry: 	at java.lang.Thread.run(Thread.java:929)
2023-09-09 22:49:08.696 GMT+02:00 I ApplicationContext: App is no longer visible.
2023-09-09 22:49:08.697 GMT+02:00 D Loki: Stopped polling.
2023-09-09 22:49:09.195 GMT+02:00 E Loki: Failed to get raw batch response
2023-09-09 22:49:09.195 GMT+02:00 E Loki: org.session.libsession.messaging.sending_receiving.pollers.PromiseCanceledException: Promise canceled.
2023-09-09 22:49:09.195 GMT+02:00 E Loki: 	at org.session.libsession.messaging.sending_receiving.pollers.Poller.poll(Poller.kt:168)
2023-09-09 22:49:09.195 GMT+02:00 E Loki: 	at org.session.libsession.messaging.sending_receiving.pollers.Poller.access$poll(Poller.kt:38)
2023-09-09 22:49:09.195 GMT+02:00 E Loki: 	at org.session.libsession.messaging.sending_receiving.pollers.Poller$poll$1$1$5.invoke(Poller.kt:262)
2023-09-09 22:49:09.195 GMT+02:00 E Loki: 	at org.session.libsession.messaging.sending_receiving.pollers.Poller$poll$1$1$5.invoke(Poller.kt:205)
2023-09-09 22:49:09.195 GMT+02:00 E Loki: 	at nl.komponents.kovenant.functional.KovenantFnMoniadic$bindAsync$1.invoke(moniadic.kt:109)
2023-09-09 22:49:09.195 GMT+02:00 E Loki: 	at nl.komponents.kovenant.functional.KovenantFnMoniadic$bindAsync$1.invoke(Unknown Source:0)
2023-09-09 22:49:09.195 GMT+02:00 E Loki: 	at nl.komponents.kovenant.jvm.KovenantJvmApi$sam$Runnable$369ad934.run(Unknown Source:2)
2023-09-09 22:49:09.195 GMT+02:00 E Loki: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2023-09-09 22:49:09.195 GMT+02:00 E Loki: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2023-09-09 22:49:09.195 GMT+02:00 E Loki: 	at java.lang.Thread.run(Thread.java:929)
2023-09-09 22:49:18.557 GMT+02:00 I ApplicationContext: App is now visible.
2023-09-09 22:49:18.564 GMT+02:00 D Loki: Started polling.
2023-09-09 22:49:18.566 GMT+02:00 D Loki: Polling https://193.219.97.147:22021.
2023-09-09 22:49:19.292 GMT+02:00 D tx: processJob: ConfigurationSyncJob (id: 16942925592910)
2023-09-09 22:49:21.905 GMT+02:00 D rx: processJob: BatchMessageReceiveJob (id: 16942925619010)
2023-09-09 22:49:22.094 GMT+02:00 I Loki: Received encrypted read receipt: (XXXXX, 1694292535161)
2023-09-09 22:49:22.110 GMT+02:00 I EarlyReceiptCache: org.thoughtcrime.securesms.database.EarlyReceiptCache@5865005
2023-09-09 22:49:22.131 GMT+02:00 I EarlyReceiptCache: Early receipt: (1694292535161, 0527552b337b4093f866955ec76b7bc62e6bd1b694fb019c58b1b21a6ef86bc179)
2023-09-09 22:49:22.249 GMT+02:00 I BatchMessageReceiveJob: Completed processing of 2 messages (id: 16942925619010)
2023-09-09 22:49:22.296 GMT+02:00 D tx: processJob: ConfigurationSyncJob (id: 16942925622920)
2023-09-09 22:49:22.468 GMT+02:00 D ConfigSyncJob: Including delete request for current hashes
2023-09-09 22:49:24.064 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
2023-09-09 22:49:24.083 GMT+02:00 I PassphraseRequiredActionBarActivity: onCreate(null)
2023-09-09 22:49:24.083 GMT+02:00 I PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
2023-09-09 22:49:24.091 GMT+02:00 I PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
2023-09-09 22:49:24.390 GMT+02:00 D ConfigSyncJob: Hash ut3a returned from store request for new config
2023-09-09 22:49:24.391 GMT+02:00 D ConfigSyncJob: Successfully removed the deleted hashes from ConversationVolatileConfig
2023-09-09 22:49:24.666 GMT+02:00 D tx: processJob: MessageSendJob (id: 16942925646590)
2023-09-09 22:49:25.310 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
2023-09-09 22:49:25.709 GMT+02:00 I PassphraseRequiredActionBarActivity: onDestroy()
2023-09-09 22:49:25.932 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
2023-09-09 22:49:25.950 GMT+02:00 I PassphraseRequiredActionBarActivity: onCreate(null)
2023-09-09 22:49:25.951 GMT+02:00 I PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
2023-09-09 22:49:25.957 GMT+02:00 I PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
2023-09-09 22:49:26.932 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
2023-09-09 22:49:27.325 GMT+02:00 I PassphraseRequiredActionBarActivity: onDestroy()
2023-09-09 22:49:27.462 GMT+02:00 D tx: processJob: ConfigurationSyncJob (id: 16942925652930)
2023-09-09 22:49:27.588 GMT+02:00 D ConfigSyncJob: Including delete request for current hashes
2023-09-09 22:49:27.643 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
2023-09-09 22:49:27.660 GMT+02:00 I PassphraseRequiredActionBarActivity: onCreate(null)
2023-09-09 22:49:27.660 GMT+02:00 I PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
2023-09-09 22:49:27.668 GMT+02:00 I PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
2023-09-09 22:49:28.830 GMT+02:00 D rx: processJob: BatchMessageReceiveJob (id: 16942925688270)
2023-09-09 22:49:28.901 GMT+02:00 I BatchMessageReceiveJob: Couldn't receive message, failed with error: Message addressed at self. (id: 16942925688270)
2023-09-09 22:49:28.913 GMT+02:00 I BatchMessageReceiveJob: Completed processing of 1 messages (id: 16942925688270)
2023-09-09 22:49:29.532 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
2023-09-09 22:49:29.548 GMT+02:00 I PassphraseRequiredActionBarActivity: onCreate(null)
2023-09-09 22:49:29.549 GMT+02:00 I PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
2023-09-09 22:49:29.557 GMT+02:00 I PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
2023-09-09 22:49:30.173 GMT+02:00 D ConfigSyncJob: Hash f65u returned from store request for new config
2023-09-09 22:49:30.174 GMT+02:00 D ConfigSyncJob: Successfully removed the deleted hashes from ConversationVolatileConfig

**Comment by m1chj** [comment]
Gave it a go again today and it's kind of fine. Just delayed like it's in Slow Mode since first message arrived 10 minutes late, second and third one arrived 14 minutes late

**Comment by bemusementpark** [comment]
Thanks a lot for the logs! It looks like a server issue. Looking into it. Thanks!

**Comment by bemusementpark** [comment]
Hi @m1chj there's been some tweaks on the backend, please try again, it should be good now, but otherwise try turning fast mode off then on again. Let me know how it goes, thanks!

**Comment by bemusementpark** [comment]
Thanks for that, thanks for the logs, looks like the issue is not resolved, raised with backend again, I'll try and repro on my Huawei device too and get back to you.
