### ISSUE TITLE
[BUG] After Android 14 Update App Won't Launch

### ISSUE THREAD

**Issue by blainebrown** [oxen-io/session-android#1337]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

App immediately crashes after trying to launch. 

Force close had no effect. 

Uninstall and reinstall booted the app. Went through setup (both as a restore and a new user) and the app crashed right after choosing Fast Mode or Slow Mode (neither choice made a difference)

### Expected Behavior

App should load list of messages. 

### Steps To Reproduce

If logged in:
Open the app
App immediately crashes

If fresh install:
Open the app
Start a new session
Choose username
Choose notification mode
App crashes

### Android Version

Android 14

### Session Version

1.17.2

### Anything else?

```
type: crash
osVersion: google/oriole/oriole:14/UP1A.231005.007/2023100900:user/release-keys
package: network.loki.messenger:3562
process: network.loki.messenger
processUptime: 196 + 231 ms
installer: com.android.packageinstaller

java.lang.RuntimeException: Unable to start activity ComponentInfo{network.loki.messenger/org.thoughtcrime.securesms.home.HomeActivity}: java.lang.SecurityException: network.loki.messenger: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3793)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3933)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.SecurityException: network.loki.messenger: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5699)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1873)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1813)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:767)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:767)
	at org.thoughtcrime.securesms.PassphraseRequiredActionBarActivity.initializeClearKeyReceiver(PassphraseRequiredActionBarActivity.java:171)
	at org.thoughtcrime.securesms.PassphraseRequiredActionBarActivity.onCreate(PassphraseRequiredActionBarActivity.java:48)
	at android.app.Activity.performCreate(Activity.java:8650)
	at android.app.Activity.performCreate(Activity.java:8628)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1461)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3775)
	... 14 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13988)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2578)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2724)
	at android.os.Binder.execTransactInternal(Binder.java:1368)
	at android.os.Binder.execTransact(Binder.java:1299)


```

**Comment by bigvtokyo** [comment]
Same for me. App wont start after GrapheneOS updated to Android 14 this morning.

**Comment by bigvtokyo** [comment]
````
type: crash
osVersion: google/bluejay/bluejay:14/UP1A.231005.007/2023100900:user/release-keys
package: network.loki.messenger:3562
process: network.loki.messenger
processUptime: 375 + 189 ms
installer: com.android.packageinstaller

java.lang.RuntimeException: Unable to start activity ComponentInfo{network.loki.messenger/org.thoughtcrime.securesms.home.HomeActivity}: java.lang.SecurityException: network.loki.messenger: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3793)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3933)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.SecurityException: network.loki.messenger: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5699)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1873)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1813)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:767)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:767)
	at org.thoughtcrime.securesms.PassphraseRequiredActionBarActivity.initializeClearKeyReceiver(PassphraseRequiredActionBarActivity.java:171)
	at org.thoughtcrime.securesms.PassphraseRequiredActionBarActivity.onCreate(PassphraseRequiredActionBarActivity.java:48)
	at android.app.Activity.performCreate(Activity.java:8650)
	at android.app.Activity.performCreate(Activity.java:8628)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1461)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3775)
	... 14 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13988)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2578)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2724)
	at android.os.Binder.execTransactInternal(Binder.java:1368)
	at android.os.Binder.execTransact(Binder.java:1299)


````

**Comment by RPGHiro** [comment]
Downgrading to 1.17.1 from f-droid also works for me.
