### ISSUE TITLE
URLs cause app crash

### ISSUE THREAD

**Issue by Sepero** [oxen-io/session-android#845]
New in v1.11.16

Some URLs cause Session to crash.

The recorded crash was from a Private Group URL.

(I also recently received a URL in 1 to 1 message and Session operated correctly)

Report from Scoop

```
FATAL EXCEPTION: main
Process: network.loki.messenger, PID: 20354
kotlin.UninitializedPropertyAccessException: lateinit property bodyTextView has not been initialized
	at org.thoughtcrime.securesms.conversation.v2.messages.LinkPreviewView.getBodyTextView(LinkPreviewView.kt:29)
	at org.thoughtcrime.securesms.conversation.v2.messages.LinkPreviewView.calculateHit(LinkPreviewView.kt:92)
	at org.thoughtcrime.securesms.conversation.v2.messages.VisibleMessageContentView$bind$2.invoke(VisibleMessageContentView.kt:135)
	at org.thoughtcrime.securesms.conversation.v2.messages.VisibleMessageContentView$bind$2.invoke(VisibleMessageContentView.kt:135)
	at org.thoughtcrime.securesms.conversation.v2.messages.VisibleMessageView.onContentClick(VisibleMessageView.kt:393)
	at org.thoughtcrime.securesms.conversation.v2.ConversationActivityV2.handlePress(ConversationActivityV2.kt:806)
	at org.thoughtcrime.securesms.conversation.v2.ConversationActivityV2.access$handlePress(ConversationActivityV2.kt:148)
	at org.thoughtcrime.securesms.conversation.v2.ConversationActivityV2$adapter$2$adapter$1.invoke(ConversationActivityV2.kt:229)
	at org.thoughtcrime.securesms.conversation.v2.ConversationActivityV2$adapter$2$adapter$1.invoke(ConversationActivityV2.kt:225)
	at org.thoughtcrime.securesms.conversation.v2.ConversationAdapter$onBindItemViewHolder$1.invoke(ConversationAdapter.kt:69)
	at org.thoughtcrime.securesms.conversation.v2.ConversationAdapter$onBindItemViewHolder$1.invoke(ConversationAdapter.kt:69)
	at org.thoughtcrime.securesms.conversation.v2.messages.VisibleMessageView.onPress(VisibleMessageView.kt:397)
	at org.thoughtcrime.securesms.conversation.v2.messages.VisibleMessageView.onUp$lambda-6(VisibleMessageView.kt:364)
	at org.thoughtcrime.securesms.conversation.v2.messages.VisibleMessageView.lambda$Js9MLefwgMkZvFfLgvOl_Zvqtzk(Unknown Source:0)
	at org.thoughtcrime.securesms.conversation.v2.messages.-$$Lambda$VisibleMessageView$Js9MLefwgMkZvFfLgvOl_Zvqtzk.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by hjubb** [comment]
Ty I'll look at getting this fixed in the next release

**Comment by hjubb** [comment]
This should be fixed now @Sepero 
let me know if it's still persisting :+1:
