### ISSUE TITLE
Cannot send message: HTTP request failed with status code 0

### ISSUE THREAD

**Issue by martin-braun** [oxen-io/session-android#879]
**Code of conduct**

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

I installed Session on two devices from F-Droid (Izzy Repository) and I can only send messages one way. On the phone on which I can send messages I cannot receive the username of my opponent, but I can receive messages on the device that fails to send messages back.

So, the affected device is unable to upload data, but it can download data. 

Sent messages show the `...` icon and the contact name of the affected device is just the SessionID on other devices (thus, the username is not uploaded as well)

**To reproduce**

- Adding the session ID of the working device on the affected device by scanning the QR code (which works, because it's only downloading)
- Receiving messages (which works on affected device)
- Replying with a message (which does not work, because it's uploading)

OR

- Adding the session ID of the affected device on the working device (does not work, because the affected device cannot upload to the loki network)

**Relevant logs**

```
2022-04-28 16:48:51.924 MESZ D Loki: POST request to https://145.239.217.124:22021/onion_req/v2 failed due to error: unexpected end of stream on Connection{145.239.217.124:22021, proxy=DIRECT hostAddress=/145.239.217.124:22021 cipherSuite=TLS_AES_128_GCM_SHA256 protocol=http/1.1}.
2022-04-28 16:48:51.926 MESZ D Loki: Couldn't reach snode at https://51.15.109.19:22021; setting failure count to 2.
2022-04-28 16:48:51.927 MESZ D Loki: Unhandled response code: 0.
2022-04-28 16:48:54.915 MESZ I PassphraseRequiredActionBarActivity: onPause()
2022-04-28 16:48:54.927 MESZ I PassphraseRequiredActionBarActivity: onCreate(null)
2022-04-28 16:48:54.927 MESZ I PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
2022-04-28 16:48:54.936 MESZ I PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
2022-04-28 16:48:59.839 MESZ D Loki: POST request to https://145.239.217.124:22021/onion_req/v2 failed due to error: unexpected end of stream on Connection{145.239.217.124:22021, proxy=DIRECT hostAddress=/145.239.217.124:22021 cipherSuite=TLS_AES_128_GCM_SHA256 protocol=http/1.1}.
2022-04-28 16:48:59.846 MESZ D Loki: Couldn't reach snode at https://213.136.74.177:23821; setting failure count to 2.
2022-04-28 16:48:59.848 MESZ D Loki: Unhandled response code: 0.
2022-04-28 16:48:59.850 MESZ E MessageSendJob: Couldn't send message due to error: org.session.libsignal.utilities.HTTP$HTTPRequestFailedException: HTTP request failed with status code 0..
2022-04-28 16:48:59.852 MESZ W MessageSendJob: Failed to send org.session.libsession.messaging.messages.control.TypingIndicator@22b97bd::class.simpleName.
2022-04-28 16:48:59.852 MESZ D MessageSendJob: Promise failed to resolve successfully
2022-04-28 16:48:59.852 MESZ D MessageSendJob: org.session.libsignal.utilities.HTTP$HTTPRequestFailedException: HTTP request failed with status code 0.
2022-04-28 16:48:59.852 MESZ D MessageSendJob: 	at org.session.libsignal.utilities.HTTP.execute(HTTP.kt:119)
2022-04-28 16:48:59.852 MESZ D MessageSendJob: 	at org.session.libsignal.utilities.HTTP.execute$default(HTTP.kt:90)
2022-04-28 16:48:59.852 MESZ D MessageSendJob: 	at org.session.libsession.snode.OnionRequestAPI$sendOnionRequest$1$1.invoke(OnionRequestAPI.kt:334)
2022-04-28 16:48:59.852 MESZ D MessageSendJob: 	at org.session.libsession.snode.OnionRequestAPI$sendOnionRequest$1$1.invoke(OnionRequestAPI.kt:332)
2022-04-28 16:48:59.852 MESZ D MessageSendJob: 	at org.session.libsignal.utilities.ThreadUtils.queue$lambda-0(ThreadUtils.kt:14)
2022-04-28 16:48:59.852 MESZ D MessageSendJob: 	at org.session.libsignal.utilities.ThreadUtils.lambda$VDXoXx8OnC_lWovEeHWLJNb73So(Unknown Source:0)
2022-04-28 16:48:59.852 MESZ D MessageSendJob: 	at org.session.libsignal.utilities.-$$Lambda$ThreadUtils$VDXoXx8OnC_lWovEeHWLJNb73So.run(Unknown Source:2)
2022-04-28 16:48:59.852 MESZ D MessageSendJob: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022-04-28 16:48:59.852 MESZ D MessageSendJob: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022-04-28 16:48:59.852 MESZ D MessageSendJob: 	at java.lang.Thread.run(Thread.java:920)
2022-04-28 16:48:59.866 MESZ I Loki: MessageSendJob failed; scheduling retry (failure count is 4).
2022-04-28 16:49:03.867 MESZ I Loki: Retrying MessageSendJob.
```

**Smartphone (please complete the following information):**

 - Device: Samsung Galaxy S10
 - OS: Android 12
 - [Session version 1.12.15](https://apt.izzysoft.de/fdroid/index/apk/network.loki.messenger)

The device is stock Android, no firewalls, no VPN, no root

**Comment by martin-braun** [comment]
It seems to work now, I wonder how it fixed itself.

**Comment by hjubb** [comment]
It might be that the destination nodes for the person you were messaging, or any of the randomized path nodes along the way we're unresponsive and as a result they got rotated out of your path
